#!/bin/bash
#====================================================================================
#
# Function: Update the kernel for Radxa E20C
# Copyright (C) 2020-- https://github.com/unifreq/openwrt_packit
# Copyright (C) 2021-- https://github.com/ophub/luci-app-amlogic
#
# Support the kernel: boot-*.tar.gz, dtb-*.tar.gz, modules-*.tar.gz
# Run openwrt-kernel after placing matching boot, dtb-rockchip and modules
# archives in the shared partition.
#
#================================== Functions list ==================================
#
# error_msg          : Output error message
# init_var           : Initialize all variables
# check_kernel       : Check kernel files list
# restore_kernel     : Restore current kernel
# update_kernel      : Update the kernel
# update_release_info : Update firmware metadata
#
#============================== Set default parameters ==============================
#
# Receive one-key command related parameters
# Set the release check file
release_file="/etc/flippy-openwrt-release"
#
#====================================================================================

# Encountered a serious error, abort the script execution
error_msg() {
    echo -e "[Error] ${1}"
    exit 1
}

# Get the partition name of the /boot file system
get_boot_partition_name() {
    local paths="/boot"
    local partition_name

    partition_name=$(df "${paths}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')

    echo "${partition_name}"
}

# Get the partition name of the root file system
get_root_partition_name() {
    local paths=("/" "/overlay" "/rom")
    local partition_name

    for path in "${paths[@]}"; do
        partition_name=$(df "${path}" | awk 'NR==2 {print $1}' | awk -F '/' '{print $3}')
        [[ -n "${partition_name}" ]] && break
    done

    echo "${partition_name}"
}

init_var() {
    # Receive one-key command related parameters
    # Check dependencies
    [[ -n "$(busybox which tar)" ]] || error_msg "Missing [ tar ] in OpenWrt firmware, unable to update kernel"

    # Check release file
    if [[ -s "${release_file}" ]]; then
        source "${release_file}"
        PLATFORM="${PLATFORM}"
        MODEL_ID="${MODEL_ID}"
        SOC="${SOC}"
        LOCK_KERNEL="${LOCK_KERNEL}"
    else
        error_msg "${release_file} file is missing!"
    fi
    [[ -n "${PLATFORM}" ]] || error_msg "Missing ${PLATFORM} value in ${release_file} file."

    # Define supported platforms
    [[ "${PLATFORM}" == rockchip && "${SOC}" == rk3528 && "${BOARD}" == e20c ]] || error_msg "Only Radxa E20C is supported."
    [[ "$(tr -d '\000' </proc/device-tree/model)" == 'Radxa E20C' ]] || error_msg "This device is not a Radxa E20C."

    # Check and repair partition mount points
    [[ -z "$(get_boot_partition_name)" || -z "$(get_root_partition_name)" ]] && {
        echo -e "Partition mount point error, start repairing..."
        openwrt-backup -g
    }

    # Set /boot/vmlinuz-* replication names for different SoCs
    MYBOOT_VMLINUZ="$(ls -l /boot/*Image 2>/dev/null | awk '{print $9}' | head -n 1)"
    MYBOOT_VMLINUZ="${MYBOOT_VMLINUZ##*/}"
    [[ -n "${MYBOOT_VMLINUZ}" ]] || error_msg "Failed to get Image name: [ ${MYBOOT_VMLINUZ} ]"

    # Find the partition where root is located
    ROOT_PTNAME="$(get_root_partition_name)"

    # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
    case "${ROOT_PTNAME}" in
    mmcblk?p[1-9])
        EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')"
        PARTITION_NAME="p"
        ;;
    [hsv]d[a-z][1-9])
        EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')"
        PARTITION_NAME=""
        ;;
    nvme?n?p[1-9])
        EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')"
        PARTITION_NAME="p"
        ;;
    *)
        error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
        ;;
    esac
    P4_PATH="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
    # Move kernel related files to the ${P4_PATH} directory
    mv -f /tmp/upload/* ${P4_PATH} 2>/dev/null

    # Current device model
    MYDEVICE_NAME="$(cat /proc/device-tree/model | tr -d '\000')"
    echo -e "Current device: ${MYDEVICE_NAME} [ ${PLATFORM} ], Use in [ ${EMMC_NAME} ]"
    sync && echo ""
}

# Check kernel files list
check_kernel() {
    cd ${P4_PATH}

    # Determine custom kernel filename
    kernel_boot="$(ls boot-*.tar.gz 2>/dev/null | head -n 1)"
    [[ -n "${kernel_boot}" ]] || error_msg "Missing boot kernel archive."
    kernel_name="${kernel_boot:5:-7}"

    KERNEL_VERSION="$(echo ${kernel_name} | grep -oE '^[1-9].[0-9]{1,3}.[0-9]+')"
    echo -e "Kernel name: ${kernel_name}"

    # check if kernel is locked
    if [ -n "${LOCK_KERNEL}" ]; then
        if [ "${LOCK_KERNEL}" != "${kernel_name}" ]; then
            if ! echo "${kernel_name}" | grep -E '^5.10.\d+-.*?rk35.*?$' >/dev/null; then
                error_msg "The kernel version is locked to [ ${LOCK_KERNEL} ], but your kernel is [ ${kernel_name} ]. "
            fi
        fi
    fi

    # Check the sha256sums file
    sha256sums_file="sha256sums"
    sha256sums_check="1"
    [[ -s "${sha256sums_file}" && -n "$(cat ${sha256sums_file})" ]] || sha256sums_check="0"
    [[ -n "$(busybox which sha256sum)" ]] || sha256sums_check="0"
    [[ "${sha256sums_check}" -eq "1" ]] && echo -e "Enable sha256sum checking..."

    # Loop check file
    i="1"
    kernel_list=("boot" "dtb-rockchip" "modules")
    for kernel_file in ${kernel_list[*]}; do
        # Set check filename
        tmp_file="${kernel_file}-${kernel_name}.tar.gz"
        # Check if file exists
        [[ -s "${tmp_file}" ]] || error_msg "The [ ${kernel_file} ] file is missing."
        # Check if the file sha256sum is correct
        if [[ "${sha256sums_check}" -eq "1" ]]; then
            tmp_sha256sum="$(sha256sum "${tmp_file}" | awk '{print $1}')"
            tmp_checkcode="$(cat ${sha256sums_file} | grep ${tmp_file} | awk '{print $1}')"
            [[ "${tmp_sha256sum}" == "${tmp_checkcode}" ]] || error_msg "${tmp_file}: sha256sum verification failed."
            echo -e "(${i}/3) [ ${tmp_file} ] file sha256sum check same."
        fi
        let i++
    done

    sync && echo ""
}

# Restore the kernel when the update fails
restore_kernel() {
    (
        cd /boot
        rm -rf \
            config-${kernel_name} \
            System.map-${kernel_name} \
            initrd.img-${kernel_name} \
            uInitrd-${kernel_name} \
            vmlinuz-${kernel_name} \
            initrd.img \
            uInitrd \
            zImage \
            Image \
            vmlinuz \
            dtb* 2>/dev/null
        tar -xzf /tmp/boot-backup.tar.gz 2>/dev/null
    )
    error_msg "Kernel update failed and has been reverted."
}

# Update the kernel
update_kernel() {
    local cur_kernel_name=$(uname -r)
    [[ "$(df -T /boot | tail -n1 | awk '{print $2}')" == ext4 ]] || error_msg "E20C requires an ext4 boot partition."
    echo -e "Start unpacking the kernel..."

    # 01. for /boot five files
    # Backup the current_kernel
    (
        cd /boot
        tar -czf /tmp/boot-backup.tar.gz \
            config-${cur_kernel_name} \
            System.map-${cur_kernel_name} \
            initrd.img-${cur_kernel_name} \
            uInitrd-${cur_kernel_name} \
            vmlinuz-${cur_kernel_name} \
            initrd.img \
            uInitrd \
            zImage \
            Image \
            vmlinuz \
            dtb* 2>/dev/null
        rm -rf \
            config-${cur_kernel_name} \
            System.map-${cur_kernel_name} \
            initrd.img-${cur_kernel_name} \
            uInitrd-${cur_kernel_name} \
            vmlinuz-${cur_kernel_name} \
            initrd.img \
            uInitrd \
            zImage \
            Image \
            vmlinuz \
            dtb* 2>/dev/null
    )
    # Extract the new kernel
    tar --no-same-owner -xf ${P4_PATH}/boot-${kernel_name}.tar.gz -C /boot

    # Check if the file exists
    local valid_files="vmlinuz-${kernel_name} uInitrd-${kernel_name} config-${kernel_name} System.map-${kernel_name}"
    rm -f /boot/initrd.img*
    for f in ${valid_files}; do [[ -f "/boot/${f}" ]] || restore_kernel; done

    # Check if the files are the same
    (
        cd /boot
        ln -sf uInitrd-${kernel_name} uInitrd
        ln -sf vmlinuz-${kernel_name} ${MYBOOT_VMLINUZ}
    )

    echo -e "(1/3) Unpacking [ boot-${kernel_name}.tar.gz ] done."

    (cd /boot && mkdir -p dtb-${kernel_name}/rockchip && ln -sf dtb-${kernel_name} dtb)
    tar --no-same-owner -xf "${P4_PATH}/dtb-rockchip-${kernel_name}.tar.gz" -C /boot/dtb/rockchip
    [[ -s "/boot/dtb/rockchip/rk3528-radxa-e20c.dtb" ]] || restore_kernel
    echo -e "(2/3) Unpacking [ dtb-rockchip-${kernel_name}.tar.gz ] done."

    # 03. for /lib/modules/*
    rm -rf /lib/modules/*
    tar --no-same-owner -xf ${P4_PATH}/modules-${kernel_name}.tar.gz -C /lib/modules
    (
        cd /lib/modules/${kernel_name}
        rm -f *.ko
        find ./ -type f -name '*.ko' -exec ln -s {} ./ \;
        sync && sleep 3
        x=$(ls *.ko -l 2>/dev/null | grep "^l" | wc -l)
        [[ "${x}" -eq "0" ]] && error_msg "Error *.ko Files not found."
    )
    echo -e "(3/3) Unpacking [ modules-${kernel_name}.tar.gz ] done."

    # Delete kernel tmpfiles
    rm -f ${P4_PATH}/*-${kernel_name}.tar.gz
    rm -f ${P4_PATH}/sha256sums

    sync && echo ""
}

# Update firmware metadata
update_release_info() {
    sed -i "s|^KERNEL_VERSION=.*|KERNEL_VERSION='${kernel_name}'|g" "${release_file}"
    sed -i "s| Kernel.*| Kernel: ${kernel_name}|g" /etc/banner 2>/dev/null
    sync
}

# Rescue the kernel
sos_kernel() {
    echo -e "Start rescuing kernel..."

    # Supports specifying disks, such as: [ openwrt-kernel -s mmcblk1 ]
    box_disk="${2}"

    if [[ -n "${box_disk}" ]]; then
        # Format the disk names
        box_disk="${box_disk//\/dev\//}"

        # Check if the disk exists
        [[ -b "/dev/${box_disk}" ]] || error_msg "The specified disk [ ${box_disk} ] does not exist."

        # Check if the disk is the same as the current system disk
        [[ "${box_disk}" == "${EMMC_NAME}" ]] && error_msg "The specified disk [ ${box_disk} ] is the same as the current system disk [ ${EMMC_NAME} ]."

        echo -e "The device name of the specified disk: [ ${box_disk} ]"
    else
        # Find emmc disk, first find emmc containing boot0 partition
        box_disk="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?|nvme[0-9]?n[0-9]?|[hsv]d[a-z])' | grep -vE ^${EMMC_NAME} | sort -u | head -n 1)"

        # Check if disk exists
        [[ -z "${box_disk}" ]] && error_msg "Unable to locate the storage requiring rescue."

        echo -e "The device name of the target disk: [ ${box_disk} ]"
    fi

    rescue_disk="/dev/${box_disk}"
    echo -e "The current OpenWrt is running on [ /dev/${EMMC_NAME} ], and the target disk for restoration is [ ${rescue_disk} ]."

    # Create a temporary mount directory
    umount ${P4_PATH}/bootfs 2>/dev/null
    umount ${P4_PATH}/rootfs 2>/dev/null
    rm -rf ${P4_PATH}/bootfs ${P4_PATH}/rootfs 2>/dev/null
    mkdir -p ${P4_PATH}/{bootfs/,rootfs/} && sync
    [[ "${?}" -ne "0" ]] && error_msg "Failed to create temporary mount directory [ ${P4_PATH} ]"

    # Mount target bootfs partition
    [[ "${box_disk}" =~ ^([hsv]d[a-z]) ]] && rescue_disk_partition_name="" || rescue_disk_partition_name="p"
    mount ${rescue_disk}${rescue_disk_partition_name}1 ${P4_PATH}/bootfs
    [[ "${?}" -ne "0" ]] && error_msg "mount ${rescue_disk}${PARTITION_NAME}1 failed!"
    echo -e "The [ ${rescue_disk}${rescue_disk_partition_name}1 ] partition is mounted on [ ${P4_PATH}/bootfs ]."

    # Search uuid file
    if [[ -f "${P4_PATH}/bootfs/uEnv.txt" ]]; then
        search_file="uEnv.txt"
    elif [[ -f "${P4_PATH}/bootfs/armbianEnv.txt" ]]; then
        search_file="armbianEnv.txt"
    elif [[ -f "${P4_PATH}/bootfs/extlinux/extlinux.conf" ]]; then
        search_file="extlinux/extlinux.conf"
    else
        error_msg "The [ uEnv.txt, armbianEnv.txt, extlinux/extlinux.conf ] file does not exist, stop rescuing."
    fi
    if [[ "${search_file}" != armbianEnv.txt ]] ||
        ! grep -q '^fdtfile=rockchip/rk3528-radxa-e20c.dtb$' "${P4_PATH}/bootfs/${search_file}"; then
        umount "${P4_PATH}/bootfs"
        error_msg "The target is not an E20C image."
    fi

    # Get the target partition uuid and rootfs
    target_parttion_uuid="$(grep '=UUID=' ${P4_PATH}/bootfs/${search_file} | sed -n 's/.*=UUID=\([a-f0-9-]*\).*/\1/p')"
    [[ -z "${target_parttion_uuid}" ]] && error_msg "The [ ${search_file} ] file does not contain the UUID value."
    target_rootfs="$(blkid | grep ${target_parttion_uuid} | awk -F':' '{print $1;}')"
    [[ -z "${target_rootfs}" ]] && error_msg "The [ ${target_parttion_uuid} ] UUID does not exist in the system."

    # Mount target rootfs partition
    mount ${target_rootfs} ${P4_PATH}/rootfs
    [[ "${?}" -ne "0" ]] && error_msg "mount ${rescue_disk}${PARTITION_NAME}2 failed!"
    echo -e "The [ ${target_rootfs} ] partition is mounted on [ ${P4_PATH}/rootfs ]."

    # Identify the current kernel files
    kernel_signature="$(uname -r)"

    # 01. For /boot files
    [[ -d "${P4_PATH}/bootfs" ]] && {
        cd ${P4_PATH}/bootfs
        rm -rf config-* initrd.img-* System.map-* vmlinuz-* uInitrd* *Image dtb* u-boot.ext u-boot.emmc
        cp -rf /boot/{*-${kernel_signature},uInitrd,*Image,dtb} .
        [[ "${?}" -ne "0" ]] && error_msg "(1/2) [ boot ] kernel files rescue failed."
        echo -e "(1/2) [ boot ] kernel files rescue succeeded."

    } || error_msg "(1/2) The [ ${P4_PATH}/bootfs ] folder does not exist, stop rescuing."

    # 02. For /lib/modules/${kernel_signature}
    [[ -d "${P4_PATH}/rootfs/lib/modules" ]] && {
        cd ${P4_PATH}/rootfs/lib/modules
        rm -rf *
        cp -rf /lib/modules/${kernel_signature} .
        [[ "${?}" -ne "0" ]] && error_msg "(2/2) [ modules ] kernel files rescue failed."
        echo -e "(2/2) [ modules ] kernel files rescue succeeded."
    } || error_msg "(2/2) The [ ${P4_PATH}/rootfs/lib/modules ] folder does not exist, stop rescuing."

    # Unmount the emmc partition
    cd ${P4_PATH}
    umount -f ${P4_PATH}/bootfs
    [[ "${?}" -ne "0" ]] && error_msg "Failed to umount [ ${P4_PATH}/bootfs ]"
    umount -f ${P4_PATH}/rootfs
    [[ "${?}" -ne "0" ]] && error_msg "Failed to umount [ ${P4_PATH}/rootfs ]"
    # Remove the temporary mount directory
    rm -rf ${P4_PATH}/bootfs ${P4_PATH}/rootfs

    sync && echo ""
}

echo -e "Welcome to the OpenWrt Kernel Management Tool."
# Operation environment check
[[ -x "/usr/sbin/openwrt-kernel" ]] || error_msg "Please grant execution permission: chmod +x /usr/sbin/openwrt-kernel"

# Execute relevant functions based on the options
if [[ "${@}" =~ ^-s(\s)* ]]; then
    # Initialize all variables
    init_var "${@}"
    # Start rescuing the kernel
    sos_kernel "${@}"

    # Kernel restore successful
    sync && sleep 3
    echo -e "Kernel rescue successful, please remove the disk and restart the OpenWrt system."
    exit 0
else
    # Initialize all variables
    init_var "${@}"
    # Check kernel files list
    check_kernel
    # Update the kernel
    update_kernel
    # Update firmware metadata
    update_release_info

    # Kernel update successful
    sync && sleep 3
    echo "Successfully updated, automatic restarting..."
    reboot
    exit 0
fi
